package com.github.sbugat.rundeckmonitor;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import javax.swing.JOptionPane;

public class VersionChecker {

	private static final String MAVEN_META_INF_DATE_COMMENT_FORMAT = "EEE MMM d HH:mm:ss zzz yyyy"; //$NON-NLS-1$

	private static final SimpleDateFormat BUILD_DATE_FORMAT = new SimpleDateFormat( MAVEN_META_INF_DATE_COMMENT_FORMAT, Locale.ENGLISH );

	public VersionChecker( final String gitHubProjectRootUrl, final String jarFileName ) {

		final String jarWithDependenciesFileName = jarFileName.replaceFirst( ".jar$" , "-jar-with-dependencies.jar" );

		try {
			final URL url = new URL( gitHubProjectRootUrl + "/blob/master/target/" + jarFileName + "?raw=true" );
			final ZipInputStream zis = new ZipInputStream( url.openStream() );

			ZipEntry entry = zis.getNextEntry();

			while( null != entry ) {

				if( entry.getName().matches( "META-INF/maven/.*/pom.properties" ) ) {

					final Date lastBuildDate = extractBuildDate( zis );

					final Date currentBuildDate = extractBuildDate( VersionChecker.class.getClassLoader().getResourceAsStream( "META-INF/maven/org.rundeck.monitor/rundeck-monitor/pom.properties" ) );

					if( lastBuildDate.after( currentBuildDate) ) {

						final int confirmDialogChoice = JOptionPane.showConfirmDialog( null, "An update is available, download it? (8-9MB)", "Rundeck Monitor update found!", JOptionPane.YES_NO_OPTION ); //$NON-NLS-1$ //$NON-NLS-2$

						if( JOptionPane.YES_OPTION == confirmDialogChoice ) {

							downloadFile( RundeckMonitorTrayIcon.RUNDECK_MONITOR_PROJECT_URL + "/blob/master/target/" + jarWithDependenciesFileName + "?raw=true", jarWithDependenciesFileName + ".update.tmp" );

							Files.move( Paths.get( jarWithDependenciesFileName + ".update.tmp" ), Paths.get( jarWithDependenciesFileName + ".update" ) );

							final ProcessBuilder processBuilder = new ProcessBuilder( getJavaExecutable().toString(), "-jar", jarWithDependenciesFileName + ".update", "update" );
							processBuilder.start();

							System.exit( 0 );
						}
					}

					break;
				}

				entry = zis.getNextEntry();
			}
		}
		catch ( final Exception e) {

			//Ignore any error during update process
			new File( jarWithDependenciesFileName + ".update.tmp" ).delete();
		}
	}

	public static void replaceJar( final String jarFileName ) {

		final String jarWithDependenciesFileName = jarFileName.replaceFirst( ".jar$" , "-jar-with-dependencies.jar" );

		try {
			Files.copy( Paths.get( jarWithDependenciesFileName + ".update" ), Paths.get( jarWithDependenciesFileName ), StandardCopyOption.REPLACE_EXISTING );

			//Restart again the process and exit
			final ProcessBuilder processBuilder = new ProcessBuilder( getJavaExecutable().toString(), "-jar", jarWithDependenciesFileName , "clean" );
			processBuilder.start();

			System.exit( 0 );
		}
		catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public static void cleanDownloadedJar( final String jarFileName ) {

		final String jarWithDependenciesFileName = jarFileName.replaceFirst( ".jar$" , "-jar-with-dependencies.jar" );

		try {
			Files.delete( Paths.get( jarWithDependenciesFileName + ".update" ) );
		}
		catch ( final IOException e ) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private static Date extractBuildDate( final InputStream inputStream ) throws IOException, ParseException {

		final BufferedReader reader = new BufferedReader( new InputStreamReader( inputStream, StandardCharsets.UTF_8 ) );

		//Ignore the first line: #Generated by Maven
		reader.readLine();

		//Read the date: #Thu Jun 26 00:02:43 CEST 2014
		final String date = reader.readLine().substring( 1 );
		return BUILD_DATE_FORMAT.parse( date );
	}

	private static void downloadFile( final String sourceFile, final String destFile ) throws IOException {

		final URL url = new URL( sourceFile );

		Files.copy( url.openStream(), Paths.get( destFile ) );
	}

	private static File getJavaExecutable() throws FileNotFoundException {

		final String javaDirectory = System.getProperty( "java.home" );

		if ( javaDirectory == null ) {
			throw new IllegalStateException("java.home");
		}

		final File javaExeFile;
		if (isWindows()) {
			javaExeFile = new File( javaDirectory, "bin/java.exe" );
		} else {
			javaExeFile = new File( javaDirectory, "bin/java" );
		}

		if ( ! javaExeFile.isFile() ) {
			throw new FileNotFoundException( javaExeFile.toString() );
		}

		return javaExeFile;
	}

	private static boolean isWindows() {

		final String operatingSystem = System.getProperty( "os.name" );

		if( null == operatingSystem ) {
			return false;
		}

		return operatingSystem.toLowerCase().startsWith("windows");
	}
}
